---
- hosts: conky #droplets, conky
  tasks:
  - name: Docker - Ubuntu
    when: ansible_distribution == "Ubuntu"
    become: true
    block:
    - name: Install prerequisites
      apt: 
        name: ['apt-transport-https','ca-certificates', 'curl', 'software-properties-common'] 
        force_apt_get: yes # apt isn't installed in the vm, forcing it to use apt-get
        # gets rid of the warning that says 'apt not found, using apt-get'
        update_cache: yes
    - name: Add Docker GPG key
      apt_key: url=https://download.docker.com/linux/ubuntu/gpg
    - name: Add Docker APT repository
      apt_repository:
        repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ansible_distribution_release}} stable
    - name: Install Docker
      apt: 
        name: docker-ce
        force_apt_get: yes
    - name: Create docker usergroup
      group:
        name: docker
        state: present
    - name: Add user to docker group
      # so that we don't have to type sudo every time we use docker
      user:
        name: "{{ansible_user}}"
        groups: docker
        append: yes
    - name: Start/Enable docker service
      systemd:
        name: docker
        state: started 
        enabled: yes

  - name: Docker - Debian
    when: ansible_distribution == "Debian"
    block:
      - name: Update the apt package index
        become: yes
        apt:
          name: "*"
          state: latest
          update_cache: yes
          force_apt_get: yes
      - name: Install packages for apt add repository over HTTPS
        become: yes
        apt:
          name: "{{ packagesdep }}"
          force_apt_get: yes
          state: latest
          update_cache: yes
        vars:
          packagesdep:
          - git
          - apt-transport-https
          - ca-certificates
          - wget
          - software-properties-common
          - gnupg2
          - curl
      - name: Add Apt signing key from official docker repo
        apt_key:
          url: https://download.docker.com/linux/debian/gpg
          state: present
      - name: add docker official repository for Debian Stretch
        apt_repository:
          repo: deb [arch=amd64] https://download.docker.com/linux/debian stretch stable
          state: present
      - name: Index new repo into the cache
        become: yes
        apt:
          name: "*"
          state: latest
          update_cache: yes
          force_apt_get: yes
      - name: actually install docker
        apt:
          name: "docker-ce"
          state: latest
  - name: Check if 'homenet' overlay exists
    ignore_errors: true
    shell: docker network inspect homenet
    register: homenet_out
  - name: Create Overlay
    when: homenet_out.rc != 0
    shell: docker network create homenet --attachable --driver overlay
  - name: Minecraft directories
    file:
      path: "{{ansible_user_dir}}/{{item}}"
      state: directory
    with_items:
      - minecraft
      - minecraft/data
  - name: Minecraft config files
    copy:
      src: "{{item}}"
      dest: "{{ansible_user_dir}}/minecraft/"
    with_items:
      - minecraft.yml
      - server.properties
      - whitelist.json
  - name: install pip
    apt:
      name: "{{packages}}"
      state: present
    vars:
      packages:
        - python-pip
        - python-setuptools
  - name: install required pip packages
    pip:
      name: [
        # required for docker_stack module
        jsondiff,
        # required for docker_stack module
        pyyaml
      ]
      extra_args: --user
  - name: Deploy minecraft.
    docker_stack:
      name: minecraft
      compose: "{{ansible_user_dir}}/minecraft/minecraft.yml"
