---
version: "3.7"
services:
  minecraft:
    image: itzg/minecraft-server
    ports:
      - 25565:25565
      # - 25575:25575
    networks:
      - homelab_homelab
    environment:
      - EULA=TRUE
      - VERSION=1.14.2
      - MODE=survival
      - MOTD="Welcome to our Minecraft server"
      # - TYPE=FORGE
      # - SPONGEVERSION=1.12.2-7.1.5
      # - PVP=false
      - OPS=kilamanila
      - "JVM_OPTS=-Xmx3072M -Xms1024M"
    configs:
      - server_properties
    volumes:
      - ./data:/data
configs:
  server_properties:
    file: ./server.properties
networks:
  homelab_homelab:
    external: true
