---
version: "3.7"
services:
  minecraft:
    image: itzg/minecraft-server
    ports:
      - 25565:25565
      # - 25575:25575
    # networks:
    #   - homelab_homelab
    environment:
      - EULA=TRUE
      - VERSION=1.14.2
      - MODE=survival
      - MOTD="Welcome to our Minecraft server"
      # - TYPE=FORGE
      # - SPONGEVERSION=1.12.2-7.1.5
      # - PVP=false
      - OPS=kilamanila
      # seems to be defaulting to 1 gig regardless of this setting
      - "JVM_OPTS=-Xmx1512M -Xms1256M"
    # configs:
    #   - server_properties
    volumes:
      - ./data:/data
      - ./whitelist.json:/data/whitelist.json
      - ./server.properties:/data/server.properties
# configs:
  # server_properties:
    # file: ./server.properties
# networks:
#   homelab_homelab:
#     external: true
